//console.log("quized");
import { showQuestion,saveAction,displayAnswer} from '/quiz-js/tracker.js';
import {UserAction } from '/quiz-js/result.js';
import { Autosave } from '/quiz-js/auto-save.js';
import { quiz } from '/quiz-js/questions.js';

/*
export const quiz = [
     {
    questionId: "1",
    questionText: "which of the following is an example of a discrete random variable ?",
    optionA: "the exact height of student in a classroom(measured in cm)",
    optionB: "The number of student presents in a classroom",
    optionC: "The amount of fuel in a car's tank (in litres)",
    optionD: "he time taken to finished marathon (in hours)",
    correct:"B",
    
  },
  {
    questionId: "2",
    questionText: "if we examine three different class squantially, and documentn the result in each of examination as F (Female) and M (Male) then the sample space is  s = {FFF,FFM,FMF,FMM,MFF,MFM,MMF,MMM} ? ",
    optionA: "4",
    optionB: "6",
    optionC: "8",
    optionD: "10",
    correct:"C",
  },
  {
    questionId: "3",
    questionText: "A coin is tossed twice. what is the probability that atleast one head occurs ? ",
    optionA: "1/4",
    optionB: "1/2",
    optionC: "3/4",
    optionD: "1",
    correct:"C",
  },
  {
    questionId: "4",
    questionText: "what is the probability of getting a total of 7 or 11 when a pair of fair dice tossed ? ",
    optionA: "1/6",
    optionB: "1/9",
    optionC: "2/9",
    optionD: "5/36 ",
    correct:"B",
  }
  ,
  {
  questionId: "5",
  questionText: "if a six men are to be arranged in a line without any restriction the total number of arrangement is ? ",
  optionA: "120",
  optionB: "360",
  optionC: "720",
  optionD: "1440 ",
  correct:"C",
  },
  {
  questionId: "6",
  questionText: "the sample space of an experiment refers to : ",
  optionA: "subset of all possible events",
  optionB: "All possible outcomes of of the experiment ",
  optionC: "the most frequent outcome",
  optionD: "None of the options  ",
  correct:"B",
  },
  {
  questionId: "7",
  questionText: "which of the following is an example of probability ? ",
  optionA: "Rolling a die",
  optionB: "Tossing a coin",
  optionC: "selecting a card from a deck",
  optionD: "All of the above ",
  correct:"D",
  },
  {
  questionId: "8",
  questionText: "if a fair cois tossed three times,what is the probability of getting exactly 2 heads ?",
  optionA: "1/4",
  optionB: "3/8",
  optionC: "1/2",
    optionD: "5/8 ",
  correct:"A",
  
  },
  {
  questionId: "9",
  questionText: "which of the following is an example of ordinal categorical data ? ",
  optionA: "Bload group (A,B,AB,O)",
  optionB: "Nationality",
  optionC: "Educational Level (Primary,secondary,University)",
    optionD: "Favorite Fruits (Mango,Apple,Banana)",
  correct:"B",
  },
  {
  questionId: "10",
  questionText: "Which type of qunatitative data represents Values that can take on any value within a range ?",
  optionA: "Ordinal data",
  optionB: "Nominal data",
  optionC: "discrete data",
    optionD: "continues data ",
  correct:"C",
  },
   {
 questionId: "11",
 questionText: " Having current knowledge and understanding of computers and mobile devices,the web and related technologies is known as :",
 optionA: "Computer literacy",
 optionB: "Digital literacy",
 optionC: "Digital safety",
     optionD: "Network literacy ",
 correct:"B",
  },
    {
 questionId: "12",
 questionText: "An input device that allows  a user to control a pointer on the screen is called a:",
 optionA: "Keyboard",
 optionB: "Scanner",
 optionC: "Mouse",
      optionD: "PLotter",
 correct:"C",
  },
     {
 questionId: "13",
 questionText: "A light sensing device that convert printed text  and images in a form that computer can process is a :",
 optionA: "Printer",
 optionB: "Display",
 optionC: "Scanner",
 optionD: "Plotter ",
 correct:"C",
 
}, {
 questionId: "14",
 questionText: "Which output device can produce solid objects like prosthetics and prototypes",
 optionA: "Inkjet printer",
 optionB: "Laser printer",
 optionC: "3D printer",
       optionD: "Thermal printer",
 correct:"C",
}
  ,
  {
    questionId:"15",
    questionText: " A worldwide collections of computer netweorks that connect millions of businesses and individuals is called",
    optionA: "The web",
    optionB: "The internet",
    optionC: "An online social network",
    optionD: "A network",
    correct:"C",
  },
  {
  questionId:"16",
  questionText: "Which hardware component conveys infromation From a computer to a user",
  optionA: "Input device",
  optionB: "Storage device",
  optionC: "Output device",
    optionD: "Communication device",
  correct:"C",
  },
    {
  questionId:"17",
  questionText: "The practice of reducing electricity consumed and environmental waste generated by computer is Known as:",
  optionA: "Green computing",
  optionB: "Digital Security",
  optionC: "computer recycling",
  optionD: "Energy resolution", 
  correct:"A",
  },
      {
  questionId:"18",
  questionText: "Another name for programme that tells computer what task to perform is :",
  optionA: "Hardware",
  optionB: "Software",
  optionC: "Data",
  optionD:"Memory",
  correct:"B",
  },
   {
  questionId:"19",
  questionText: "The process od setting up a program  to work is called :",
  optionA: "Running",
  optionB: "Interfacing",
  optionC: "Developing",
  optionD:"Installing" ,
  correct:"D",
 },  {
  questionId:"20",
  questionText: "A collections of computers and devices connected together via communication device is:",
  optionA: "Server",
  optionB: "web",
  optionC: "network",
  optionD:"cloud",
  correct:"C",
 },  {
  questionId:"21",
  questionText: "Which of the following is text based name that correspond to device's IP adress ? ",
  optionA: "DNS server",
  optionB: "Web addres",
  optionC: "Domain Name",
  optionD:"ISP",
  correct:"C",
 },  {
  questionId:"22",
  questionText: "The first page that website is known as :",
  optionA: "Landing page",
  optionB: "Home page",
  optionC: "Index page",
  optionD:"web portal",
  correct:"B",
  },
    {
  questionId:"",
  questionText: "",
  optionA: "",
  optionB: "",
  optionC: "",
  optionD:""
 }


];


*/
//buttons selector filed
/*let name = prompt("Enter your name please");
const userName = document.querySelector(".user-name");
userName.innerText = `${name.toLocaleUpperCase()}`;
*/
const body = document.querySelector("body");
//console.log(body);






const previosButton = document.querySelector(".previous-button");
const nextButton = document.querySelector(".next-button");
const submitButton = document.querySelector(".submit-button");
const gotoButton = document.querySelector('.goto-button');
export const questionSpan = document.querySelector('.question-progress');
const totalQuestions = document.querySelector('.total-questions');
//console.log(questionSpan, totalQuestions);
/*
 const QoptionA = document.querySelector(".optionA");
 const QoptionB = document.querySelector(".optionB");
 const QoptionC = document.querySelector(".optionC");
const QoptionD = document.querySelector(".optionD");
 */
//console.log(gotoButton);
export const notificationContainer = document.querySelector(".submit-notification");

  notificationContainer.style.display = "none";
document.querySelector(".goto-container").style.display = "none";



let GotoButtonsHtml = '';

/*
const gotoButton = document.querySelector(".goto-button");
const cancelButton = document.querySelector(".cancel-buttons");
const gotoContainer = document.querySelector(".goto-container");
gotoButton.addEventListener("click", () => {
  gotoContainer.style.display = "flex";
})
cancelButton.addEventListener("click", () => {
  gotoContainer.style.display = "none";
})
*/
/*---------------- */

/*const Qnumber = document.querySelector(".question-number");
const Qtext = document.querySelector('.question-text');
const QoptionA = document.querySelector(".optionA");
const QoptionB = document.querySelector(".optionB");
const QoptionC = document.querySelector(".optionC");
const QoptionD = document.querySelector(".optionD");
*/
/*function showQuestion() {
  Qnumber.textContent = quiz[index].questionId;
  Qtext.textContent = quiz[index].questionText;
  QoptionA.textContent = quiz[index].optionA;
  QoptionB.textContent = quiz[index].optionB;
  QoptionC.textContent = quiz[index].optionC;
  QoptionD.textContent = quiz[index].optionD;
  options.forEach(
    input => {
      input.checked = false;
    }
  );
  options.forEach(input => {
    input.addEventListener("change", () => {
      answers[index] = input.value;
    });
    //let save = answers[index];
     if (answers[index] !== null) {
        document.querySelector(`input[value="${answers[index]}"]`).checked = true;
    }
})
  
};*/
/*function clearUserState() {
  optA.checked = false;
  optB.checked = false;
  optC.checked = false;
  optD.checked = false;
}*/







 const QoptionA = document.querySelector(".optionA");
 const QoptionB = document.querySelector(".optionB");
 const QoptionC = document.querySelector(".optionC");
 const QoptionD = document.querySelector(".optionD");

  export let index = 0;
  const lastIndex = quiz.length - 1;
export const options = document.querySelectorAll("input[name='a']");
export let answers = Array(quiz.length).fill(null);
totalQuestions.innerHTML = `${quiz.length}`;
showQuestion();


body.addEventListener('keydown', () => {
  //console.log(key === "keyN");
  if (event.key.toUpperCase() === "n".toUpperCase()) {
    nextAction();
  }
  else if (event.key.toUpperCase() === 'p'.toUpperCase()) {
    previousAction();
  }
  else if (event.key.toUpperCase() === 'g'.toUpperCase()) {
    document.querySelector(".goto-container").style.display = "flex";
  }
  else if (event.key.toUpperCase() === 's'.toUpperCase()) {
    //renderResultPreview();
    UserAction()
  }
 
  else if (event.key.toUpperCase() === 'a'.toUpperCase()) {
    //console.log("A has pressed")
     //input.checked = true;
    options[0].checked = true;
    answers[index] = options[0].value;
    displayAnswer(index);
  }
  else if (event.key.toUpperCase() === 'b'.toUpperCase()) {
    //console.log("B was pressed");
     //input.checked = true;
    options[1].checked = true;
    answers[index] = options[1].value;
    displayAnswer(index);
  }
  else if (event.key.toUpperCase() === "c".toUpperCase()) {
    //console.log("C has pressed")
     //input.checked = true;
    options[2].checked = true;
    answers[index] = options[2].value;
    displayAnswer(index);
  }
  else if (event.key.toUpperCase() === "d".toUpperCase()) {
    //console.log("D has pressed");
     //input.checked = true;
    options[3].checked = true;
    answers[index] = options[3].value;
    displayAnswer(index);
  }
});





  function updateButtons(index) {
    for (let i = 0; i < buttons_Array.length; i++) {
      if (index === index) {
        buttons_Array.forEach(
          btn => {
            btn.classList.remove("current-index");
          }
        )
        buttons_Array[index].classList.add("current-index");
      }
      break
    }
};
function nextAction() {
      if (index < lastIndex) {
   index++;
   showQuestion();
        updateButtons(index);
        previosButton.classList.remove("last-index");
        
  }
  if (index === lastIndex) {
    nextButton.classList.add("last-index");
    //console.log("is last");
     previosButton.classList.remove("last-index");
  }
  
};
function previousAction() {
  if (index > 0) {
  index--;
  showQuestion();
  updateButtons(index);
    previosButton.classList.remove("last-index");
    nextButton.classList.remove('last-index');
  }
  if (index === 0) {
    previosButton.classList.add("last-index");
    nextButton.classList.remove('last-index');
  }
}
  
nextButton.addEventListener('click', () => {
  nextAction();
  });
  previosButton.addEventListener("click", () => {
    previousAction();
  });

/*function UserAction() {
  answers.forEach((question) => {
    if (question === quiz[index].correct) {
      result.corrects++;
    }
    else if (question === null) {
      result.skips++;
    } else {
      result.wrongs++;
    }
  })
  console.log(result.corrects * 5, result.wrongs * 5, result.skips);
  alert(`total = ${result.corrects + result.wrongs + result.skips},
    marks = ${result.corrects * 10},
    skips = ${result.skips}
    ${(result.corrects)*10}/${(result.corrects+result.wrongs+result.skips)*10}
    
    `);
  }*/
let buttons = "";
quiz.forEach((question,index) => {
  buttons += `<button  id="current-index${index}" class="question-button">${index + 1} </button>`;
});
GotoButtonsHtml = `<span>${buttons}</span>`;
document.querySelector(".goto-container").innerHTML = `<div>${GotoButtonsHtml}</div>
 <div class="closed-button-container">
<span class="closed-button">X</span>
   </div>`;
const closedButton = document.querySelector(".closed-button");
//console.log(closedButton);
closedButton.addEventListener("click",button=> {
  document.querySelector(".goto-container").style.display = "none";
});
gotoButton.addEventListener('click', () => {
  document.querySelector(".goto-container").style.display = "flex";
});
export const buttons_Array = document.querySelectorAll(".goto-container button");



buttons_Array[0].classList.add("current-index");
buttons_Array.forEach((button, position) => {              
  button.addEventListener("click", () => {
    index = position;
    nextButton.classList.remove("last-index");
    previosButton.classList.remove("last-index");
    showQuestion();
        if (handleButtonRenderation(index, position)) {
          buttons_Array.forEach(btn => {
            btn.classList.remove("current-index");
          });
          button.classList.add("current-index");
        };
        }
  );
      
});

submitButton.addEventListener("click", () => {
  //renderResultPreview();
  UserAction();
});
Autosave();

function handleButtonRenderation(currentIndex,position) {
  //console.log("i handled it ");
  let index = 0;
  if (position === currentIndex) {
    //console.log("match found");
    return true;
  }
  else {
    return false 
  }
}
function checkAnswer(index) {
if (answers[index] !== null)
{
  return true;
  }
else {
  return false 
  }
}

/*const stateManager = {
  answered: false,
  currentIndex: 1,
  visitedIndex: 10,
};
*/